version: '3.8'  # ок, игнор warning
services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file: 
      - .env  # ← из .env!
    networks: [backend-net]
    restart: unless-stopped

  postgres:
    image: postgres:16
    env_file:
      - .env  # ← из .env!
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      retries: 5
    networks: [backend-net]
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    volumes: [pgadmin-data:/var/lib/pgadmin]
    depends_on: [postgres]
    networks: [backend-net]
    restart: unless-stopped

  # npm:
  #   image: jc21/nginx-proxy-manager:latest
  #   ports:
  #     - '8081:80'
  #     - '8443:443'
  #     - '81:81'
  #   volumes:
  #     - npm-data:/data
  #     - npm-lets:/etc/letsencrypt
  #   networks: [backend-net]
  #   restart: unless-stopped

networks:
  backend-net:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
  #npm-data:
  #npm-lets:
